  
version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    commands:
      - echo Install nvm for latest Node
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - NVM_DIR=/root/.nvm
      - chmod +x ~/.nvm/nvm.sh
      - set +a . /root/.nvm/nvm.sh && source /root/.nvm/nvm.sh && nvm install --lts
      - echo Installing dependency...
      - npm install --legacy-peer-deps -g next
      - npm install --legacy-peer-deps
      
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run export
artifacts:
  files:
    - '**/*'
  base-directory: 'out'